security:
    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    encoders:
        Hillrange\Security\Entity\User:
            algorithm: bcrypt
            cost:      15
    providers:
        App\Core\Provider\UserProvider:
            entity:
                class:              Hillrange\Security\Entity\User
                property:           username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: hillrange_security_login
                check_path: hillrange_security_login

            # activate different ways to authenticate

            # http_basic: ~
            # https://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # https://symfony.com/doc/current/cookbook/security/form_login_setup.html
