App\Entity\Staff:
    properties:
        staffType:
            - \App\Core\Validator\SettingChoice:
                name: 'staff.categories'
            - NotBlank: ~
        jobTitle:
            - NotBlank: ~
        house:
            - \App\Core\Validator\SettingChoice:
                name: 'house.list'
                settingDataValue: 'name'

