App\Entity\User:
    type: entity
    table: user
    repositoryClass: App\Repository\UserRepository
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: [username]
            errorPath: username
            message: 'The User Name must be unique.'
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: [email]
            errorPath: email
            message: 'The EMail must be unique.'
    indexes:
        username:
            columns: [ username ] 
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 64
            unique: true
        usernameCanonical:
            type: string
            length: 64
            unique: true
            column: username_canonical
        email:
            type: string
            length: 64
            unique: true
        emailCanonical:
            type: string
            length: 64
            unique: true       
            column: email_canonical
        enabled:
            type: boolean
        locale:
            type: string
            length: 10
        password:
            type: string
            length: 64 
        lastLogin:
            column: last_login
            type: datetime
            nullable: true
        locked:
            type: boolean
        expired:
            type: boolean
        expiresAt:
            column: expires_at
            type: datetime
            nullable: true
        confirmationToken:
            type: string
            column: confirmation_token
            nullable: true 
        passwordRequestedAt:
            column: password_requested_at
            type: datetime
            nullable: true
        credentialsExpired:
            type: boolean 
            column: credentials_expired
        credentialsExpireAt:
            column: credentials_expire_at
            type: datetime
            nullable: true
        groups:
            type: array
            nullable: true
        directroles:
            type: array
            nullable: true
            column: direct_roles
        lastModified:
            type: datetime
            column: last_modified
        createdOn:
            type: datetime
            column: create_on
#    oneToOne:
#        year:
#            targetEntity: App\Entity\Year
#            nullable: true
    manyToOne:
        createdBy:
            targetEntity: App\Entity\User
            joinColumns:
                created_by:
                    referencedColumnName: id
                    nullable: true
        modifiedBy:
            targetEntity: App\Entity\User
            joinColumns:
                modified_by:
                    referencedColumnName: id
                    nullable: true
